package com.mdr.offline.utilities

val languageNames = mapOf(
    "af" to "Afrikaans",
    "ar" to "Arabic",
    "az" to "Azerbaijani",
    "be" to "Belarusian",
    "bg" to "Bulgarian",
    "bn" to "Bengali",
    "ca" to "Catalan",
    "cs" to "Czech",
    "cy" to "Welsh",
    "da" to "Danish",
    "de" to "German",
    "el" to "Greek",
    "en" to "English",
    "eo" to "Esperanto",
    "es" to "Spanish",
    "et" to "Estonian",
    "eu" to "Basque",
    "fa" to "Persian",
    "fi" to "Finnish",
    "fr" to "French",
    "ga" to "Irish",
    "gl" to "Galician",
    "gu" to "Gujarati",
    "he" to "Hebrew",
    "hi" to "Hindi",
    "hr" to "Croatian",
    "hu" to "Hungarian",
    "hy" to "Armenian",
    "id" to "Indonesian",
    "is" to "Icelandic",
    "it" to "Italian",
    "ja" to "Japanese",
    "ka" to "Georgian",
    "kk" to "Kazakh",
    "km" to "Khmer",
    "kn" to "Kannada",
    "ko" to "Korean",
    "lt" to "Lithuanian",
    "lv" to "Latvian",
    "mk" to "Macedonian",
    "ml" to "Malayalam",
    "mn" to "Mongolian",
    "mr" to "Marathi",
    "ms" to "Malay",
    "my" to "Burmese",
    "nb" to "Norwegian",
    "ne" to "Nepali",
    "nl" to "Dutch",
    "pl" to "Polish",
    "pt" to "Portuguese",
    "pt-br" to "Portuguese (Brazil)",
    "ro" to "Romanian",
    "ru" to "Russian",
    "sk" to "Slovak",
    "sl" to "Slovenian",
    "sq" to "Albanian",
    "sr" to "Serbian",
    "sv" to "Swedish",
    "sw" to "Swahili",
    "ta" to "Tamil",
    "te" to "Telugu",
    "th" to "Thai",
    "tl" to "Filipino",
    "tr" to "Turkish",
    "uk" to "Ukrainian",
    "ur" to "Urdu",
    "uz" to "Uzbek",
    "vi" to "Vietnamese",
    "zh" to "Chinese",
    "zh-hk" to "Chinese (Traditional)",
    "zh-ro" to "Chinese (Romanized)"
)

fun String.toLanguageName(): String = languageNames[this.lowercase()] ?: this